server:
  port: 8090

spring:
  datasource:
      url: jdbc:h2:mem:localdb
      username: hema
      driver: org.h2.Driver
      password: hema
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true